### ISSUE TITLE
Can't login with Native token - format changed in 0.11.2

### ISSUE THREAD

**Issue by stmyers** [owenfarrell/vscode-vault#1]
As of Vault 0.11.2, the token is no longer a UUID format, but a base62 format  (see https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#0112-october-2nd-2018).

Currently cannot login with a token ("not a valid token" error)

**Comment by owenfarrell** [comment]
@stmyers So I had a bit of cleanup to do based on the news about the compromised event-stream. But I added an additional option to validate native tokens.

I don't have access to a Vault instance that is >=0.11.2. Based on your experience, do you think my regex is safe? Or can I make it a bit more strict based on length?

**Comment by stmyers** [comment]
Sorry for delayed response.  I think you might want to avoid the check entirely or just make it less explicit...Hashi already changed it again because of service/batch token types.

From https://www.vaultproject.io/docs/concepts/tokens.html:
>Note that external to Vault, tokens are to be considered opaque values by users and as such, their structure is both currently undocumented and subject to change.

**Comment by owenfarrell** [comment]
I'm trying to think through the implications not sanitizing the data via a whitelisting function. But as long as there there isn't a standard (or a commitment to a standard), I guess we'll have to go with the simple approach.

Any last thoughts?

**Comment by stmyers** [comment]
Sounds reasonable to me, thanks!

**Comment by msabramo** [comment]
Would you please push a new build with this fix to the VS Code Marketplace?
