### ISSUE TITLE
Icons too accessible

### ISSUE THREAD

**Issue by sroughto** [owenfarrell/vscode-vault#61]
I feel like the icons (copy, update, delete) are uncomfortably close together; i.e., too easy to click "delete" accidentally. The pop-up dialog does help prevent this, but it still feels a bit too easy. Perhaps you could add a setting that disables these buttons during regular use; i.e., a readonly mode. Then click the gear and toggle "readonly" to enable edit mode. Just a thought.

Also, I keep wanting press cmd-C to copy the whole secret to json (but not cmd-V to paste!). Selecting a particular attribute from the drop-down list is ok too.

**Comment by owenfarrell** [comment]
👋 Hi @sroughto,

> I feel like the icons (copy, update, delete) are uncomfortably close together

Yeah, I hear what you're saying. When it comes to the VSCode API for creating custom `TreeItem` instances, I'm not aware of a way to change the spacing. How do you feel about demoting the `delete` action from an icon to the context menu? The VSCode docs have an example image [here](https://code.visualstudio.com/api/extension-guides/tree-view#view-actions) where a `Delete` action is part of the context menu.

> Perhaps you could add a setting that disables these buttons during regular use; i.e., a readonly mode.

One of the challenges here is that it would challenging to deal with a change on-the-fly. For example, toggling this kind of setting on/off would require a wholesale reload of the panel. Not impossible, but pretty intensive.

> Also, I keep wanting press cmd-C to copy the whole secret to json (but not cmd-V to paste!). Selecting a particular attribute from the drop-down list is ok too.

Adding a "Copy" action to pull the whole secret as a JSON blob is definitely possible. I'm not sure what it would take to integrate with keyboard shortcuts, but certainly worth exploring.

Would you have any interest in taking on one of these enhancements?

**Comment by owenfarrell** [comment]
Doing a quick look around, it looks like triggering a command on a `TreeItem` via a keypress isn't working (blocked by https://github.com/microsoft/vscode/issues/72442).
