### ISSUE TITLE
Can't authenticate with GitHub

### ISSUE THREAD

**Issue by Thatkookooguy** [owenfarrell/vscode-vault#85]
When going through the process of the `Vault: Connect to Server` wizard, when selecting github as the authentication method, the wizard asks me to generate a personal access token. Even though the token was generated in github, I get the following error:

![image](https://user-images.githubusercontent.com/10427304/161843961-967b563c-9290-472e-b6d5-c6390df6ee88.png)

**Comment by owenfarrell** [comment]
Hey @Thatkookooguy - thanks for the heads up. This looks like a (relatively) simple fix based on the new token formats. I'll take a look this week.
