### ISSUE TITLE
Extension adds a `+` button to EVERY accordion in vscode

### ISSUE THREAD

**Issue by Thatkookooguy** [owenfarrell/vscode-vault#86]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/10427304/162232688-3fdf2ee2-cc81-476a-bdd7-a2536887c6fa.png">

<img width="643" alt="Screen Shot 2022-04-07 at 18 14 09" src="https://user-images.githubusercontent.com/10427304/162233018-6e352966-da78-4398-a17e-341bc67e7a19.png">

**Comment by owenfarrell** [comment]
@Thatkookooguy - Sorry for the delay here. I decided to take on a new CI/CD pipeline pattern that supports VSCode's pre-release mechanism. In that spirit, I've just pushed out a pre-release that contains a fix to this issue as well as a fix to #85.

If you uninstall the extension and reload VSCode, you should see a dropdown that enables you to pull the pre-release (see [here](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions) for the official instructions).

Any feedback you have would be super helpful!

~Owen
